version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: docere_postgres
    environment:
      POSTGRES_USER: docere_user
      POSTGRES_PASSWORD: 89EozvNk1rCBwRIXwEhXYRzE6fNh46Iu
      POSTGRES_DB: docere
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
